#
macro(fst_parse_version VERSION_FILE_PATH)
    file(READ ${VERSION_FILE_PATH} VERSION_STRING)
    string(REPLACE "." ";" VERSION_LIST ${VERSION_STRING})
    list(GET VERSION_LIST 0 FST_VERSION_MAJOR)
    list(GET VERSION_LIST 1 FST_VERSION_MINOR)
    list(GET VERSION_LIST 2 FST_VERSION_PATCH)
    list(GET VERSION_LIST 3 FST_VERSION_BUILD)
endmacro()

#
macro(fst_add_version_definition TARGET_NAME)
    target_compile_definitions(
        ${TARGET_NAME} PUBLIC -DFST_VERSION_MAJOR=${FST_VERSION_MAJOR} -DFST_VERSION_MINOR=${FST_VERSION_MINOR}
                              -DFST_VERSION_PATCH=${FST_VERSION_PATCH} -DFST_VERSION_BUILD=${FST_VERSION_BUILD})
endmacro()
